/* This script owns search, language/theme preferences, API calls and safe rendering. */
const WEATHER_API='https://api.open-meteo.com/v1/forecast';
const AIR_API='https://air-quality-api.open-meteo.com/v1/air-quality';
const GEOCODE_API='https://geocoding-api.open-meteo.com/v1/search';
const state={language:localStorage.getItem('weatherLanguage')||'my',location:null};
const aliases={'ရန်ကုန်':'Yangon','မန္တလေး':'Mandalay','နေပြည်တော်':'Naypyidaw','တောင်ကြီး':'Taunggyi','မော်လမြိုင်':'Mawlamyine','ပဲခူး':'Bago','ပုသိမ်':'Pathein','မုံရွာ':'Monywa','ထားဝယ်':'Dawei','မြိတ်':'Myeik','စစ်တွေ':'Sittwe','လွိုင်ကော်':'Loikaw','မြစ်ကြီးနား':'Myitkyina','လားရှိုး':'Lashio','မူဆယ်':'Muse','ပြင်ဦးလွင်':'Pyin Oo Lwin','ညောင်ရွှေ':'Nyaungshwe'};
const i18n={my:{eyebrow:'ယနေ့အတွက် ရာသီဥတု',headline:'ဘယ်နေရာမှာ မိုးရွာမလဲ?',subheadline:'မြို့ သို့မဟုတ် မြို့နယ်နာမည်ကို ရှာပါ။',search:'ရှာရန်',useLocation:'⌖ လက်ရှိနေရာ',loading:'ဒေတာရယူနေသည်…',currentWeather:'လက်ရှိရာသီဥတု',feelsLike:'ခံစားရသည်',rainfall:'မိုးရေချိန်',next24h:'လာမည့် ၂၄ နာရီ',rainChance:'မိုးရွာနိုင်ချေ',airQuality:'လေထုအရည်အသွေး',uvIndex:'UV အညွှန်း',humidity:'စိုထိုင်းဆ',relative:'စိုထိုင်းဆ',wind:'လေတိုက်နှုန်း',sevenDay:'၇ ရက် ခန့်မှန်းချက်',details:'အသေးစိတ်အချက်အလက်',pressure:'လေဖိအား',visibility:'မြင်ကွင်း',sunrise:'နေထွက်',sunset:'နေဝင်',disclaimer:'ခန့်မှန်းချက်သည် မော်ဒယ်ဒေတာဖြစ်ပြီး တရားဝင်ဘေးအန္တရာယ်သတိပေးချက် မဟုတ်ပါ။ အရေးပေါ်အခြေအနေတွင် သက်ဆိုင်ရာအာဏာပိုင်များ၏ ထုတ်ပြန်ချက်ကိုသာ လိုက်နာပါ။'},en:{eyebrow:'Weather for today',headline:'What is the weather like?',subheadline:'Search for any city or township.',search:'Search',useLocation:'⌖ My location',loading:'Loading data…',currentWeather:'Current weather',feelsLike:'Feels like',rainfall:'Rainfall',next24h:'Next 24 hours',rainChance:'Rain chance',airQuality:'Air quality',uvIndex:'UV index',humidity:'Humidity',relative:'Relative humidity',wind:'Wind',sevenDay:'7-day forecast',details:'Details',pressure:'Pressure',visibility:'Visibility',sunrise:'Sunrise',sunset:'Sunset',disclaimer:'Forecast values are model data, not official emergency warnings. Follow local authorities during emergencies.'}};
const $=id=>document.getElementById(id);const tr=k=>i18n[state.language][k]||k;
function setText(){document.documentElement.lang=state.language;document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=tr(e.dataset.i18n));$('languageToggle').textContent=state.language==='my'?'EN':'MM';$('locationInput').placeholder=state.language==='my'?'မြို့ / မြို့နယ် ရှာရန်':'Search city / township';}
function setTheme(){const dark=localStorage.getItem('weatherTheme')==='dark';document.documentElement.dataset.theme=dark?'dark':'light';$('themeToggle').textContent=dark?'☀':'☾';}
function showStatus(message){$('status').textContent=message;$('status').hidden=false}function hideStatus(){$('status').hidden=true}function loading(on){$('loading').hidden=!on}
function weatherText(code){const my={0:'ကြည်လင်',1:'အများအားဖြင့် ကြည်လင်',2:'တိမ်အနည်းငယ်',3:'တိမ်ထူ',45:'မြူ',48:'မြူထူ',51:'မိုးဖွဲ',53:'မိုးဖွဲ',55:'မိုးဖွဲများ',61:'မိုး',63:'မိုးရွာ',65:'မိုးသည်း',71:'နှင်း',73:'နှင်းကျ',75:'နှင်းထူ',80:'မိုးကျဲ',81:'မိုးရွာ',82:'မိုးသည်း',95:'မိုးကြိုးမုန်တိုင်း',96:'မိုးကြိုးမုန်တိုင်း',99:'မိုးကြိုးမုန်တိုင်း'};const en={0:'Clear sky',1:'Mostly clear',2:'Partly cloudy',3:'Cloudy',45:'Foggy',48:'Foggy',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Snow',73:'Snow',75:'Heavy snow',80:'Rain showers',81:'Rain showers',82:'Heavy showers',95:'Thunderstorm',96:'Thunderstorm with hail',99:'Thunderstorm with hail'};return(state.language==='my'?my:en)[code]||'—'}
function icon(code){if(code===0)return'☀️';if([1,2].includes(code))return'🌤️';if(code===3)return'☁️';if([45,48].includes(code))return'🌫️';if([71,73,75,77].includes(code))return'❄️';if([95,96,99].includes(code))return'⛈️';return'🌧️'}
function aqiLabel(v){if(v==null)return'—';if(state.language==='my')return v<=50?'ကောင်းမွန်':v<=100?'အသင့်အတင့်':v<=150?'ထိခိုက်နိုင်':'မကောင်း';return v<=50?'Good':v<=100?'Moderate':v<=150?'Unhealthy for sensitive groups':'Unhealthy'}
function uvLabel(v){if(v==null)return'—';if(state.language==='my')return v<3?'နိမ့်':v<6?'အလယ်အလတ်':v<8?'မြင့်':'အလွန်မြင့်';return v<3?'Low':v<6?'Moderate':v<8?'High':'Very high'}
function time(iso){return iso?iso.slice(11,16):'—'}
async function geocode(query){const normalized=aliases[query.trim()]||query.trim();const res=await fetch(`${GEOCODE_API}?name=${encodeURIComponent(normalized)}&count=10&language=en&format=json`);if(!res.ok)throw Error('geocode');const results=(await res.json()).results||[];const mm=results.filter(x=>x.country_code==='MM');if(!mm.length)throw Error('notfound');return mm[0]||results[0]}
function saveRecent(place){let items=JSON.parse(localStorage.getItem('weatherRecent')||'[]').filter(x=>x.name!==place.name);items.unshift({name:place.name,latitude:place.latitude,longitude:place.longitude});localStorage.setItem('weatherRecent',JSON.stringify(items.slice(0,5)));renderRecent()}
function renderRecent(){const wrap=$('recentLocations');wrap.innerHTML='';JSON.parse(localStorage.getItem('weatherRecent')||'[]').forEach(item=>{const b=document.createElement('button');b.className='chip';b.textContent=item.name;b.onclick=()=>load(item);wrap.appendChild(b)})}
function set(id,value){$(id).textContent=value??'—'}
function renderForecast(d){const box=$('forecast');box.innerHTML='';d.time.forEach((date,i)=>{const row=document.createElement('div');const day=i===0?(state.language==='my'?'ယနေ့':'Today'):new Intl.DateTimeFormat(state.language==='my'?'my-MM':'en-US',{weekday:'short'}).format(new Date(`${date}T12:00`));row.className='forecast-item';row.innerHTML=`<strong>${day}</strong><span class="forecast-icon">${icon(d.weather_code[i])}</span><small>${Math.round(d.precipitation_probability_max?.[i]||0)}% · ${weatherText(d.weather_code[i])}</small><strong>${Math.round(d.temperature_2m_max[i])}° / ${Math.round(d.temperature_2m_min[i])}°</strong>`;box.appendChild(row)})}
async function load(place){loading(true);hideStatus();try{const params='current=temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,rain,weather_code,pressure_msl,visibility,wind_speed_10m,wind_direction_10m&hourly=precipitation_probability,precipitation&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,precipitation_probability_max,uv_index_max,sunrise,sunset&forecast_days=7&timezone=auto&wind_speed_unit=kmh';const airParams='current=us_aqi,pm2_5,pm10&timezone=auto';const [wr,ar]=await Promise.all([fetch(`${WEATHER_API}?latitude=${place.latitude}&longitude=${place.longitude}&${params}`),fetch(`${AIR_API}?latitude=${place.latitude}&longitude=${place.longitude}&${airParams}`)]);if(!wr.ok)throw Error('weather');const w=await wr.json();const a=ar.ok?await ar.json():{};const c=w.current,d=w.daily,h=w.hourly,ac=a.current||{};const rain=(d.precipitation_sum||[]).slice(0,1)[0]||0;const chance=h.precipitation_probability?.[0]||d.precipitation_probability_max?.[0]||0;set('locationName',place.name||'—');set('locationMeta',`${place.admin1||'Myanmar'} · ${place.latitude.toFixed(2)}, ${place.longitude.toFixed(2)}`);set('updatedAt',`${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} · ${w.timezone_abbreviation||''}`);set('temperature',Math.round(c.temperature_2m));set('condition',weatherText(c.weather_code));set('feelsLike',Math.round(c.apparent_temperature));$('weatherIcon').textContent=icon(c.weather_code);set('rainfall',`${Number(rain).toFixed(1)} mm`);set('rainChance',`${Math.round(chance)}%`);set('aqi',ac.us_aqi==null?'—':Math.round(ac.us_aqi));set('aqiDetail',aqiLabel(ac.us_aqi));set('uvIndex',d.uv_index_max?.[0]==null?'—':Number(d.uv_index_max[0]).toFixed(1));set('uvDetail',uvLabel(d.uv_index_max?.[0]));set('humidity',`${Math.round(c.relative_humidity_2m)}%`);set('wind',`${Math.round(c.wind_speed_10m)} km/h`);set('windDirection',`${Math.round(c.wind_direction_10m)}°`);set('pressure',`${Math.round(c.pressure_msl)} hPa`);set('visibility',`${(c.visibility/1000).toFixed(1)} km`);set('sunrise',time(d.sunrise?.[0]));set('sunset',time(d.sunset?.[0]));set('pm25',ac.pm2_5==null?'—':`${Number(ac.pm2_5).toFixed(1)} µg/m³`);set('pm10',ac.pm10==null?'—':`${Number(ac.pm10).toFixed(1)} µg/m³`);renderForecast(d);$('dashboard').hidden=false;state.location=place;saveRecent(place)}catch(e){$('dashboard').hidden=true;showStatus(e.message==='notfound'?(state.language==='my'?'မြို့/မြို့နယ် မတွေ့ပါ။ အင်္ဂလိပ်လို သို့မဟုတ် မြန်မာလို ပြန်ရှာပါ။':'Location not found. Try another city or township.'): (state.language==='my'?'ဒေတာရယူမရပါ။ အင်တာနက်ချိတ်ဆက်မှုကို စစ်ပါ။':'Unable to load weather data. Check your connection.'))}finally{loading(false)}}
async function search(){const q=$('locationInput').value.trim();if(!q)return;try{await load(await geocode(q))}catch(e){showStatus(state.language==='my'?'မြို့/မြို့နယ် မတွေ့ပါ။':'Location not found.')}}
$('searchForm').onsubmit=e=>{e.preventDefault();search()};$('currentLocation').onclick=()=>{if(!navigator.geolocation)return showStatus('Geolocation is not supported.');loading(true);navigator.geolocation.getCurrentPosition(p=>load({name:state.language==='my'?'လက်ရှိနေရာ':'My location',latitude:p.coords.latitude,longitude:p.coords.longitude}),()=>{loading(false);showStatus(state.language==='my'?'Location ခွင့်ပြုချက် လိုအပ်ပါသည်။':'Location permission is required.')})};$('languageToggle').onclick=()=>{state.language=state.language==='my'?'en':'my';localStorage.setItem('weatherLanguage',state.language);setText();if(state.location)load(state.location)};$('themeToggle').onclick=()=>{localStorage.setItem('weatherTheme',localStorage.getItem('weatherTheme')==='dark'?'light':'dark');setTheme()};
setTheme();setText();renderRecent();$('locationInput').value='Mandalay';load({name:'Mandalay',latitude:21.9588,longitude:96.0891});
